CREATE DATABASE IF NOT EXISTS photon;
USE photon;

CREATE TABLE IF NOT EXISTS users(user_id INT PRIMARY KEY NOT NULL, username VARCHAR(255) NOT NULL, displayname VARCHAR(255), pass VARCHAR(255) NOT NULL, avatar VARCHAR(255), bio TEXT(2000));
CREATE TABLE IF NOT EXISTS galleries(owner_id INT PRIMARY KEY NOT NULL, gallery_id INT, thumb VARCHAR(255), description VARCHAR(255), uploaded DATETIME);
CREATE TABLE IF NOT EXISTS photos(photo_id INT PRIMARY KEY NOT NULL, ref MEDIUMBLOB, gallery_id INT, datetaken DATETIME, fstop VARCHAR(255), iso VARCHAR(255), model VARCHAR(255), lens VARCHAR(255));

CREATE USER IF NOT EXISTS 'mgr'@'%' IDENTIFIED BY 'pword';
GRANT ALTER, CREATE, DELETE, INDEX, INSERT, UPDATE, SELECT ON `photon`.* TO 'mgr';
FLUSH PRIVILEGES;
